//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Account.java
//  @ Date : 2018-08-29
//  @ Author : 
//
//




public class Account
{
	public String accountCode;
	public String accName;
	public String saupNo;
	public Object repreName;
	public String uptae;
	public String upJong;
	public String upDamBang;
	public Date accStartDate;
	public Date accEndDate;
	public Date gylDate;
	public Date napLeadDate;
	public void accountList()
	{
	
	}
}
