//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Car.java
//  @ Date : 2018-08-29
//  @ Author : 
//
//




public class Car
{
	public int speed;
	public String color;
	public void speedUp()
	{
	
	}
	
	public void speedDown()
	{
	
	}
}
