//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : carTest.java
//  @ Date : 2018-08-29
//  @ Author : 
//
//




public class carTest
{
	public Object main(args, String);
	public void main(Object String[], Object args)
	{
	
	}
}
