//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : categoCodeMaster.java
//  @ Date : 2018-08-29
//  @ Author : 
//
//




public class categoCodeMaster
{
	public String bigPartCode;
	public String smallPartCode;
	public String name;
}
