//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : employee.java
//  @ Date : 2018-08-29
//  @ Author : 
//
//




public class employee
{
	public String empNo;
	public String name;
	public String password;
	public Object businessAuth;
}
