//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : goods.java
//  @ Date : 2018-08-29
//  @ Author : 
//
//




public class goods
{
	public String goodCode;
	public String goodName;
	public int jaegiPrice;
	public int buTaxper;
	public char autoOrderGu;
	public int profitPer;
	public void goodProduct()
	{
	
	}
}
