//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : maker.java
//  @ Date : 2018-08-29
//  @ Author : 
//
//




public class maker
{
	public String product;
}
