//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : orderDetail.java
//  @ Date : 2018-08-29
//  @ Author : 
//
//




public class orderDetail
{
	public String ordersunNo;
	public String unit;
	public int quantity;
	public int price;
	public int amount;
	public Date baeDate;
	public void orderPro()
	{
	
	}
}
