//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : orderHeader.java
//  @ Date : 2018-08-29
//  @ Author : 
//
//




public class orderHeader
{
	public String orderData;
	public String junpyoNo;
	public String unsongGu;
}
