//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Professor.java
//  @ Date : 2018-08-29
//  @ Author : 
//
//




public class Professor
{
	public String name;
}
