//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : purchaseHeader.java
//  @ Date : 2018-08-29
//  @ Author : 
//
//




public class purchaseHeader
{
	public String purDate;
	public String purNo;
	public String purGuBun;
	public String perRefGu;
	public int purTotal;
	public int buTax;
	public int gita;
	public char gylTypet;
	public void purchaseSiljuk()
	{
	
	}
}
