//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : purchaseDetail.java
//  @ Date : 2018-08-29
//  @ Author : 
//
//




public class purchaseDetail
{
	public String orderNo;
	public String unit;
	public int quantity;
	public int price;
	public int amount;
	public Date baeDate;
}
