//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : School.java
//  @ Date : 2018-08-29
//  @ Author : 
//
//




public class School
{
	public String name;
	public String address;
	public void addStudent()
	{
	
	}
	
	public void removeStudent()
	{
	
	}
}
