//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : shop.java
//  @ Date : 2018-08-29
//  @ Author : 
//
//




public class shop
{
	public String shopCode;
	public String areaInfo;
}
