//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Study.java
//  @ Date : 2018-08-29
//  @ Author : 
//
//




public class Study
{
	public String name;
	public int studyNo;
	public Object maxCount;
	public void addStudent()
	{
	
	}
	
	public void removeStudent()
	{
	
	}
}
