//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Student.java
//  @ Date : 2018-08-29
//  @ Author : 
//
//




public class Student
{
	public String name;
	public int hakbun;
}
